pipeline {
    agent any
    
    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
		YOUR_DOCKERHUB_USERNAME=filibuster
        YOUR_DOCKERHUB_PASSWORD=41yASA
        SERVICE_NAME = "backend-app-service"
        REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${SERVICE_NAME}:${BUILD_ID}"
	}
    
    stages {
        stage('Make some actions depending on ENV') {
            steps {
                script {
                    if (params.ENV == "TEST") {
                        sh 'echo "This id TEST env"'
                    } elif (params.ENV == "PROD") {
                        sh 'echo "This id PROD env"'
                    }
                }
            }
        }
        stage('Build docker image') {
            steps {
                sh 'docker build --file backend/Dockerfile -t ${REPOSITORY_TAG} backend/'
            }
        }
        stage('Login to DockerHub') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}
        stage('Push docker image to registry') {
            steps {
                sh 'docker push ${REPOSITORY_TAG}'
            }
        }
         stage('Deploy to Cluster') {
          steps {
                    sh 'envsubst < ${WORKSPACE}/backend/deploy.yaml | kubectl apply -f -'
            }
        }
    }
    
    post {
		always {
			sh 'docker logout'
		}
	}
}
